### ISSUE TITLE
TypeError on deploy of upm-grove-rgb-lcd

### ISSUE THREAD

**Issue by AgriVision** [w4ilun/Node-Red-Node-UPM#8]
I get a "TypeError: LCD.Jhd1313m1 is not a function" error when deploying a node using upm-grove-rgb-lcd on an Intel edison.

**Comment by w4ilun** [comment]
Latest version should address this issue. jsupm_Jhd1313m1 is part of UPM v1.3.0, the node now falls back to jsupms_i2clcd if it's unavailable.
